#!/bin/bash
cordova platform remove android \
&& cordova plugin add cordova-plugin-android-permissions \
&& cordova plugin add cordova-plugin-device \
&& cordova plugin add phonegap-nfc \
&& cordova plugin add cordova-plugin-network-information \
&& cordova platform add android@11.0.0 \
&& cordova build \
&& cordova run android
